#!/bin/bash
export LANG=ja_JP.UTF-8;
here=$(dirname $(readlink -f $0))
iuml=$here/iuml
java -Djava.io.tmpdir=/var/tmp -Djava.awt.headless=true -Dplantuml.include.path="$iuml" -jar $here/plantuml.jar -charset UTF-8 ${@}
