' # [@ gdon] Gdoc GdObject Notation
'
' ## [@] Gdoc Object Classes
'
@startuml GdocObjectClass

!include style.iuml

class GdObject {
    id : str
    class : {category, type, version}
    __
    parent : GdObject
    children : { id: GdObject }
    properties : { key: value }
}

GdObject <|-- "Example.SysML:Requirement"

GdObject <|-- "Example.Gdoc:Section"

"Example.Gdoc:Section" -right- "0..*" "Example.SysML:Requirement"

"Example.GSN:Goal" -right-|> "Example.Gdoc:Section"

@enduml


@startuml SectionDataStructure

!include style.iuml
!include SysML/bdd.iuml

skinparam class {
    BackgroundColor<<Gdoc Element>> Wheat
    BorderColor<<PandocAst>> Tomato
}

class Document <<Gdoc Element>>
class Section <<Gdoc Element>>
class "     BlockList     " as BlockList <<Gdoc Element>>
class TextBlock <<Gdoc Element>>
class ListBlock <<Gdoc Element>>

class Pandoc <<PandocAst>>
class Header <<PandocAst>>
class Plain <<PandocAst>>
class Para <<PandocAst>>
class LineBlock <<PandocAst>>

class CodeBlock <<PandocAst>>
class RawBlock <<PandocAst>>
class Table <<PandocAst>>

class BulletList <<PandocAst>>
class OrderedList <<PandocAst>>

Document -down-|> Section
Document <|-right- Pandoc

Section -down-|> BlockList

BlockList o-up- Section
BlockList o-- TextBlock
BlockList o-- ListBlock
BlockList o-- CodeBlock
BlockList o-- RawBlock

BlockList o-- Table
BlockList --o Table

TextBlock <|-- Header
TextBlock <|-- Plain
TextBlock <|-- Para
TextBlock <|-- LineBlock

ListBlock o-- BlockList
ListBlock <|-- BulletList
ListBlock <|-- OrderedList

@enduml


@startuml TextBlockDataStructure

!include style.iuml
!include SysML/bdd.iuml

skinparam class {
    BackgroundColor<<Gdoc Element>> Wheat
    BorderColor<<PandocAst>> Tomato
}

class TextBlock <<Gdoc Element>>
class Line <<Gdoc Element>>
class Tag <<Gdoc Element>>
class Text <<Gdoc Element>>
class String <<Gdoc Element>>

class Str <<PandocAst>>
class Space <<PandocAst>>
class SoftBreak <<PandocAst>>
class LineBreak <<PandocAst>>
class Code <<PandocAst>>
class Math <<PandocAst>>
class Image <<PandocAst>>
class Quoted <<PandocAst>>

Line -up-o TextBlock
LineBreak -up-o TextBlock

Tag -up-o Line
Text -up-o Line

String -up-o Tag

String -up-o Text
Code -up-o Text
Math -up-o Text
Image -up-o Text
Quoted -up-o Text

Str -up-o String
Space -up-o String
SoftBreak -up-o String

note as N1
  It may contain line breaks, but
  they are ignored when splitting
  a text block into lines.
end note

Image .. N1
Quoted .. N1

@enduml


@startuml GdocObjectStructure

!include style.iuml
!include SysML/bdd.iuml

skinparam class {
    BackgroundColor<<Gdoc Element>> Wheat
    BorderColor<<PandocAst>> Tomato
}

class Document <<Gdoc Element>>

class Section <<Gdoc Element>>
class "     BlockList     " as BlockList <<Gdoc Element>>
class TextBlock <<Gdoc Element>>
class ListBlock <<Gdoc Element>>

class CodeBlock <<PandocAst>>
class RawBlock <<PandocAst>>
class Table <<PandocAst>>

Document -down-|> Section
Section -down-|> BlockList

BlockList o-up- Section
BlockList o-- TextBlock
BlockList o-- CodeBlock
BlockList o-- RawBlock
BlockList o-- Table
BlockList --o Table

BlockList o-- ListBlock
ListBlock o-- BlockList

class Line <<Gdoc Element>>
class Tag <<Gdoc Element>>
class Text <<Gdoc Element>>
class String <<Gdoc Element>>

class Str <<PandocAst>>
class Space <<PandocAst>>
class SoftBreak <<PandocAst>>
class LineBreak <<PandocAst>>
class Code <<PandocAst>>
class Math <<PandocAst>>
class Image <<PandocAst>>
class Quoted <<PandocAst>>

Line -up-o TextBlock
LineBreak -up-o TextBlock

Tag -up-o Line
Text -up-o Line

String -up-o Tag

String -up-o Text
Code -up-o Text
Math -up-o Text
Image -up-o Text
Quoted -up-o Text

Str -up-o String
Space -up-o String
SoftBreak -up-o String

@enduml


